namespace GenericSynthesisPatcher.Helpers
{
    /// <summary>
    ///     Represents the type of log entry that can be generated by the patcher.
    ///
    ///     Uppercase values shouldn't be used, but should use the ProperCase versions instead.
    /// </summary>
    [Flags]
    public enum LogType
    {
        OTHER = 0,

        // Related log was positive, successful, or otherwise good.
        SUCCESS = 1 << 0,

        // Related log was negative, failed, or otherwise bad.
        FAILURE = 1 << 1,

        // Related log was skipped, not processed, or otherwise not applicable.
        SKIPPED = 1 << 2,

        // Related log is related to configuration provided by user.
        CONFIG = 1 << 3,

        // Related log is related to matching records or properties.
        MATCH = 1 << 4,

        // Related log is related to origin of the record (Master or Not).
        ORIGIN = 1 << 5,

        // Related log is related to an action being performed.
        ACTION = 1 << 6,

        // Related log is related to a record being processed or updated.
        RECORD = 1 << 7,

        // Related log is related to a cache operation, such as reading or writing to the cache.
        Cache = 1 << 8,

        // General configuration log or successful config action.
        GeneralConfig = CONFIG | SUCCESS,

        // General configuration log of something negative or failed.
        GeneralConfigFailure = CONFIG | FAILURE,

        // Rule(s) being skipped for some reason.
        SkippingRule = CONFIG | SKIPPED,

        // Record filtering matched filter
        MatchSuccess = MATCH | SUCCESS,

        // Record filtering did not match filter
        MatchFailure = MATCH | FAILURE,

        // Record matched origin
        OriginMatch = ORIGIN | MATCH | SUCCESS,

        // Record did not match origin - skipping
        OriginNotMatch = ORIGIN | MATCH | FAILURE | SKIPPED,

        // Record being processed is not overwritten, and is the original master record.
        NoOverwrites = RECORD | ORIGIN | SKIPPED,

        // Lookup for a record in config was successful (ie. EditorID found, Forward from record found)
        RecordFound = CONFIG | ACTION | SUCCESS,

        // Lookup for a record in config was not successful (ie. EditorID not found)
        RecordNotFound = CONFIG | ACTION | FAILURE,

        // Property was found on a record
        PropertyNotExist = CONFIG | RECORD | FAILURE,

        // Property action invalid (value was not successfully read from configuration / action not supported)
        RecordActionInvalid = CONFIG | RECORD | ACTION | FAILURE,

        // Log processing a record but not yet determined if updated or not
        RecordProcessing = RECORD | ACTION,

        // Log processing a record action was skipped (partially or fully) due something action
        // specific and not NoUpdateAlreadyMatches
        RecordProcessSkipped = RECORD | ACTION | FAILURE | SKIPPED,

        // Record updated attempted but failed
        RecordUpdateFailure = RECORD | ACTION | FAILURE,

        // Record updated successfully
        RecordUpdated = RECORD | ACTION | SUCCESS,

        // Value being set already matched current value
        NoUpdateAlreadyMatches = RECORD | ACTION | SKIPPED,
    }
}